#!/bin/bash

chmod +x ~/binder/start.neo4j 

# starting neo4j
~/binder/start.neo4j   &



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"