#!/bin/bash

mkdir logs


chmod +x ~/binder/start.neo4j 
chmod +x ~/binder/start.vscode 

# starting neo4j
~/binder/start.neo4j   &

# starting vscode in parallel
~/binder/start.vscode   &


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"